env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:import/typescript
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - plugin:react/recommended
  - plugin:react/jsx-runtime
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
rules: 
  '@typescript-eslint/type-annotation-spacing': [error, {before: true, after: true, overrides: {colon: {before: false, after: true}}}]
  '@typescript-eslint/member-delimiter-style': [error, {multiline: {delimiter: semi}}]
  import/extensions: ['error', 'ignorePackages', {'ts': 'never', 'tsx': 'never'}]
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
